server:
  port: 8123
spring:
  datasource:
    #连接MySQL
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/film_db?useSSL=false
    username: root
    password: 123456
mybatis:
    configuration:
##配置项：开启下划线到驼峰的自动转换. 作用：将数据库字段根据驼峰规则自动注入到对象属性。
      map-underscore-to-camel-case: true
logging:
  level:
    #打印SQL信息
    com.yx.springboot.demospring.mybatis.mapper: debug